name: Go Multi-Platform Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build
      run: |
        CGO_ENABLED=1 \
        GOOS=darwin \
        GOARCH=amd64 \
        go build -v -tags=darwin -o bitcoin-tracker-darwin-amd64

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bitcoin-tracker-darwin-amd64
        path: bitcoin-tracker-darwin-amd64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: bitcoin-tracker-darwin-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}